name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan filesystem
        run: trivy fs .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (with cache)
  run: docker build --cache-from=deploylynx/naturalfit-devsecops:latest -t deploylynx/naturalfit-devsecops:latest .
  
      - name: Scan Docker image
        run: trivy image deploylynx/naturalfit-devsecops:latest

      - name: Push Docker image
        run: docker push deploylynx/naturalfit-devsecops:latest