name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 60s
        command_timeout: 10m
        script: |
          set -e
          docker stop naturalfit || true
          docker rm naturalfit || true
          docker pull deploylynx/naturalfit-devsecops:latest
          docker run -d -p 3000:3000 --name naturalfit deploylynx/naturalfit-devsecops:latest
